package com.philemonworks.rtunes.controllers.stub
{
	// TrackControllerStub is generated by Pocogese FlexGenerator on Mon, 23 Jul 2007 18:06:15 GMT

	import com.philemonworks.flex.net.Command;
	import com.philemonworks.flex.net.RestClient;
	import com.philemonworks.rtunes.controllers.api.TrackController;
	
	public class TrackControllerStub implements com.philemonworks.rtunes.controllers.api.TrackController {
		private var _baseURL:String;
		
		// Constructor
		public function TrackControllerStub(baseURL:String = "") {
			super()
			this._baseURL = baseURL
		}	
		/**
		 * Command API function. The _replyReceivedHandler function (optional) will be called with a Reply object
		 */
		function destroy(id:String,_replyReceivedHandler:Function = null):void {
			trace('TrackController#destroy(id)')
			_replyReceivedHandler.call(this, new Reply())
		}
		/**
		 * Command API function. The _replyReceivedHandler function (optional) will be called with a Reply object
		 */
		function saveOrUpdate(recordXML:String,_replyReceivedHandler:Function = null):void {
			trace('TrackController#saveOrUpdate(recordXML)')
			_replyReceivedHandler.call(this, new Reply())
		}

		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find(id:String,_xmlReceivedHandler:Function):void {
			trace('TrackController#find(id)')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function findAll(_xmlReceivedHandler:Function):void {
			trace('TrackController#findAll()')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_albums(_xmlReceivedHandler:Function):void {
			trace('TrackController#find_all_albums()')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_artists(_xmlReceivedHandler:Function):void {
			trace('TrackController#find_all_artists()')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_by_album(album:String,_xmlReceivedHandler:Function):void {
			trace('TrackController#find_all_by_album(album)')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_by_artist(artist:String,_xmlReceivedHandler:Function):void {
			trace('TrackController#find_all_by_artist(artist)')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_by_genre(genre:String,_xmlReceivedHandler:Function):void {
			trace('TrackController#find_all_by_genre(genre)')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_genres(_xmlReceivedHandler:Function):void {
			trace('TrackController#find_all_genres()')
			_xmlReceivedHandler.call(this,</>)		
		}
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function listPage(from:String,to:String,sortkey:String,sortmethod:String,_xmlReceivedHandler:Function):void {
			trace('TrackController#listPage(from,to,sortkey,sortmethod)')
			_xmlReceivedHandler.call(this,</>)		
		}
			
	}
}