package com.philemonworks.rtunes.controllers.api
{
	// TrackController is generated by Pocogese FlexGenerator on Mon, 23 Jul 2007 18:06:15 GMT
	
	public interface TrackController
	{
		/**
		 * Command API function. The _replyReceivedHandler function (optional) will be called with a Reply object
		 */
		function destroy(id:String,_replyReceivedHandler:Function = null):void;
		/**
		 * Command API function. The _replyReceivedHandler function (optional) will be called with a Reply object
		 */
		function saveOrUpdate(recordXML:String,_replyReceivedHandler:Function = null):void;

		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find(id:String,_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function findAll(_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_albums(_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_artists(_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_by_album(album:String,_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_by_artist(artist:String,_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_by_genre(genre:String,_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function find_all_genres(_xmlReceivedHandler:Function):void;
		/**
		 * Selection API function.  _xmlReceivedHandler is called with an XML object
		 */
		function listPage(from:String,to:String,sortkey:String,sortmethod:String,_xmlReceivedHandler:Function):void;
	
	}
}